siteTitle: Marcus Fade
tagline: Premium Cuts & Grooming
theme: fade
accentColor: ''
logo: null
favicon: null
socialLinks:
  - platform: instagram
    url: https://instagram.com/marcusfade
  - platform: tiktok
    url: https://tiktok.com/@marcusfade
  - platform: facebook
    url: https://facebook.com/marcusfade
  - platform: yelp
    url: https://yelp.com/biz/marcus-fade
phone: '(312) 555-0187'
email: marcus@marcusfade.com
footerText: Â© 2025 Marcus Fade. All rights reserved.
